package com.nixkey.bridge

import androidx.test.platform.app.InstrumentationRegistry
import androidx.test.runner.AndroidJUnit4
import com.nixkey.keystore.ConfirmationPolicy
import com.nixkey.keystore.KeyManager
import com.nixkey.keystore.KeyType
import com.nixkey.keystore.SignRequestQueue
import com.nixkey.keystore.SignRequestStatus
import io.grpc.ManagedChannelBuilder
import io.grpc.Status
import io.grpc.StatusRuntimeException
import java.util.concurrent.TimeUnit
import java.util.concurrent.atomic.AtomicReference
import nixkey.v1.NixKey.ListKeysRequest
import nixkey.v1.NixKey.PingRequest
import nixkey.v1.NixKey.SignRequest as GrpcSignRequest
import nixkey.v1.NixKeyAgentGrpc
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Integration test for the Go gRPC phone server running in the Android process.
 *
 * Starts [GoPhoneServer] with real [KeyManager] and [SignRequestQueue],
 * connects a gRPC client, and exercises all RPCs (ListKeys, Sign, Ping).
 *
 * Prerequisites:
 * - Run `make gomobile` to build the phoneserver AAR into android/app/libs/
 * - The proto stubs are generated by the protobuf Gradle plugin at build time
 */
@RunWith(AndroidJUnit4::class)
class GoPhoneServerTest {

    private lateinit var goPhoneServer: GoPhoneServer
    private lateinit var keyManager: KeyManager
    private lateinit var signRequestQueue: SignRequestQueue

    @Before
    fun setUp() {
        val context = InstrumentationRegistry.getInstrumentation().targetContext
        keyManager = KeyManager(context)
        signRequestQueue = SignRequestQueue()
        goPhoneServer = GoPhoneServer(keyManager, signRequestQueue)
    }

    @After
    fun tearDown() {
        goPhoneServer.stop()
    }

    @Test
    fun serverStartsAndStops() {
        goPhoneServer.start("127.0.0.1:0")
        Thread.sleep(500)
        assertTrue("Server should be running", goPhoneServer.isRunning())
        assertTrue("Port should be assigned", goPhoneServer.port() > 0)

        goPhoneServer.stop()
        assertFalse("Server should be stopped", goPhoneServer.isRunning())
    }

    @Test(expected = IllegalStateException::class)
    fun doubleStartThrows() {
        goPhoneServer.start("127.0.0.1:0")
        Thread.sleep(500)
        goPhoneServer.start("127.0.0.1:0")
    }

    @Test
    fun pingRpcReturnsTimestamp() {
        goPhoneServer.start("127.0.0.1:0")
        Thread.sleep(500)

        val channel = ManagedChannelBuilder
            .forAddress("127.0.0.1", goPhoneServer.port())
            .usePlaintext()
            .build()
        try {
            val stub = NixKeyAgentGrpc.newBlockingStub(channel)
            val before = System.currentTimeMillis()
            val resp = stub.ping(PingRequest.getDefaultInstance())
            val after = System.currentTimeMillis()

            assertTrue(
                "Timestamp should be in range [$before, $after], got ${resp.timestampMs}",
                resp.timestampMs in before..after,
            )
        } finally {
            channel.shutdownNow()
        }
    }

    @Test
    fun listKeysReturnsCreatedKeys() {
        val keyInfo = keyManager.createKey("test-grpc-key", KeyType.ECDSA_P256)

        try {
            goPhoneServer.start("127.0.0.1:0")
            Thread.sleep(500)

            val channel = ManagedChannelBuilder
                .forAddress("127.0.0.1", goPhoneServer.port())
                .usePlaintext()
                .build()
            try {
                val stub = NixKeyAgentGrpc.newBlockingStub(channel)
                val resp = stub.listKeys(ListKeysRequest.getDefaultInstance())

                assertTrue("Should have at least 1 key", resp.keysCount >= 1)
                val found = resp.keysList.any { it.fingerprint == keyInfo.fingerprint }
                assertTrue("Should find test key by fingerprint", found)
            } finally {
                channel.shutdownNow()
            }
        } finally {
            keyManager.deleteKey(keyInfo.alias)
        }
    }

    @Test
    fun signRpcWithApproval() {
        val keyInfo = keyManager.createKey(
            "test-sign-key",
            KeyType.ECDSA_P256,
            ConfirmationPolicy.ALWAYS_ASK,
        )

        try {
            goPhoneServer.start("127.0.0.1:0")
            Thread.sleep(500)

            // Auto-approve the sign request from a background thread
            val approveThread = Thread {
                waitForRequest()
                val current = signRequestQueue.currentRequest.value ?: return@Thread
                signRequestQueue.complete(current.requestId, SignRequestStatus.APPROVED)
                goPhoneServer.confirmerAdapter.notifyCompletion(
                    current.requestId,
                    SignRequestStatus.APPROVED,
                )
            }
            approveThread.start()

            val channel = ManagedChannelBuilder
                .forAddress("127.0.0.1", goPhoneServer.port())
                .usePlaintext()
                .build()
            try {
                val stub = NixKeyAgentGrpc.newBlockingStub(channel)
                val req = GrpcSignRequest.newBuilder()
                    .setKeyFingerprint(keyInfo.fingerprint)
                    .setData(com.google.protobuf.ByteString.copyFrom("test data".toByteArray()))
                    .setFlags(0)
                    .build()
                val resp = stub.sign(req)

                assertNotNull("Should get a signature", resp.signature)
                assertTrue("Signature should not be empty", resp.signature.size() > 0)
            } finally {
                channel.shutdownNow()
                approveThread.join(5000)
            }
        } finally {
            keyManager.deleteKey(keyInfo.alias)
        }
    }

    @Test
    fun signRpcDeniedByUser() {
        val keyInfo = keyManager.createKey(
            "test-deny-key",
            KeyType.ECDSA_P256,
            ConfirmationPolicy.ALWAYS_ASK,
        )

        try {
            goPhoneServer.start("127.0.0.1:0")
            Thread.sleep(500)

            // Deny the sign request from a background thread
            val denyThread = Thread {
                waitForRequest()
                val current = signRequestQueue.currentRequest.value ?: return@Thread
                signRequestQueue.complete(current.requestId, SignRequestStatus.DENIED)
                goPhoneServer.confirmerAdapter.notifyCompletion(
                    current.requestId,
                    SignRequestStatus.DENIED,
                )
            }
            denyThread.start()

            val channel = ManagedChannelBuilder
                .forAddress("127.0.0.1", goPhoneServer.port())
                .usePlaintext()
                .build()
            try {
                val stub = NixKeyAgentGrpc.newBlockingStub(channel)
                val req = GrpcSignRequest.newBuilder()
                    .setKeyFingerprint(keyInfo.fingerprint)
                    .setData(com.google.protobuf.ByteString.copyFrom("test data".toByteArray()))
                    .setFlags(0)
                    .build()

                try {
                    stub.sign(req)
                    assertTrue("Should have thrown on denial", false)
                } catch (e: StatusRuntimeException) {
                    assertEquals(
                        "Should be PERMISSION_DENIED",
                        Status.PERMISSION_DENIED.code,
                        e.status.code,
                    )
                }
            } finally {
                channel.shutdownNow()
                denyThread.join(5000)
            }
        } finally {
            keyManager.deleteKey(keyInfo.alias)
        }
    }

    @Test
    fun signRpcTimeoutReturnsDeadlineExceeded() {
        val keyInfo = keyManager.createKey(
            "test-timeout-key",
            KeyType.ECDSA_P256,
            ConfirmationPolicy.ALWAYS_ASK,
        )

        try {
            goPhoneServer.start("127.0.0.1:0")
            Thread.sleep(500)

            // Do NOT approve or deny — let the request hang until client deadline expires
            val channel = ManagedChannelBuilder
                .forAddress("127.0.0.1", goPhoneServer.port())
                .usePlaintext()
                .build()
            try {
                val stub = NixKeyAgentGrpc.newBlockingStub(channel)
                    .withDeadlineAfter(2, TimeUnit.SECONDS)
                val req = GrpcSignRequest.newBuilder()
                    .setKeyFingerprint(keyInfo.fingerprint)
                    .setData(com.google.protobuf.ByteString.copyFrom("timeout data".toByteArray()))
                    .setFlags(0)
                    .build()

                try {
                    stub.sign(req)
                    assertTrue("Should have thrown on timeout", false)
                } catch (e: StatusRuntimeException) {
                    assertEquals(
                        "Should be DEADLINE_EXCEEDED",
                        Status.DEADLINE_EXCEEDED.code,
                        e.status.code,
                    )
                }
            } finally {
                channel.shutdownNow()
                // Unblock the server-side ConfirmerAdapter latch so tearDown doesn't hang
                val pending = signRequestQueue.currentRequest.value
                if (pending != null) {
                    signRequestQueue.complete(pending.requestId, SignRequestStatus.TIMEOUT)
                    goPhoneServer.confirmerAdapter.notifyCompletion(
                        pending.requestId,
                        SignRequestStatus.TIMEOUT,
                    )
                }
            }
        } finally {
            keyManager.deleteKey(keyInfo.alias)
        }
    }

    @Test
    fun signRequestCarriesCorrectConfirmationPolicy() {
        val keyInfo = keyManager.createKey(
            "test-policy-key",
            KeyType.ECDSA_P256,
            ConfirmationPolicy.BIOMETRIC,
        )

        try {
            goPhoneServer.start("127.0.0.1:0")
            Thread.sleep(500)

            // Approve from background, but capture the policy from the SignRequest
            val policyRef = AtomicReference<ConfirmationPolicy>()
            val fingerprintRef = AtomicReference<String>()
            val approveThread = Thread {
                waitForRequest()
                val current = signRequestQueue.currentRequest.value ?: return@Thread
                policyRef.set(current.confirmationPolicy)
                fingerprintRef.set(current.keyFingerprint)
                signRequestQueue.complete(current.requestId, SignRequestStatus.APPROVED)
                goPhoneServer.confirmerAdapter.notifyCompletion(
                    current.requestId,
                    SignRequestStatus.APPROVED,
                )
            }
            approveThread.start()

            val channel = ManagedChannelBuilder
                .forAddress("127.0.0.1", goPhoneServer.port())
                .usePlaintext()
                .build()
            try {
                val stub = NixKeyAgentGrpc.newBlockingStub(channel)
                val req = GrpcSignRequest.newBuilder()
                    .setKeyFingerprint(keyInfo.fingerprint)
                    .setData(com.google.protobuf.ByteString.copyFrom("policy test".toByteArray()))
                    .setFlags(0)
                    .build()
                stub.sign(req)
                approveThread.join(5000)

                assertEquals(
                    "SignRequest should carry the key's BIOMETRIC policy",
                    ConfirmationPolicy.BIOMETRIC,
                    policyRef.get(),
                )
                assertEquals(
                    "SignRequest should carry the key's fingerprint",
                    keyInfo.fingerprint,
                    fingerprintRef.get(),
                )
            } finally {
                channel.shutdownNow()
                approveThread.join(5000)
            }
        } finally {
            keyManager.deleteKey(keyInfo.alias)
        }
    }

    private fun waitForRequest() {
        var attempts = 0
        while (signRequestQueue.currentRequest.value == null && attempts < 50) {
            Thread.sleep(100)
            attempts++
        }
    }
}
